// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	domain "github.com/startup-of-zero-reais/COD-courses-api/domain"
	mock "github.com/stretchr/testify/mock"
)

// ArtifactService is an autogenerated mock type for the ArtifactService type
type ArtifactService struct {
	mock.Mock
}

// Add provides a mock function with given fields: artifact
func (_m *ArtifactService) Add(artifact domain.Artifact) (*domain.Artifact, error) {
	ret := _m.Called(artifact)

	var r0 *domain.Artifact
	if rf, ok := ret.Get(0).(func(domain.Artifact) *domain.Artifact); ok {
		r0 = rf(artifact)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Artifact)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.Artifact) error); ok {
		r1 = rf(artifact)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: lessonId
func (_m *ArtifactService) List(lessonId string) ([]domain.Artifact, error) {
	ret := _m.Called(lessonId)

	var r0 []domain.Artifact
	if rf, ok := ret.Get(0).(func(string) []domain.Artifact); ok {
		r0 = rf(lessonId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Artifact)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(lessonId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Remove provides a mock function with given fields: artifactId
func (_m *ArtifactService) Remove(artifactId string) error {
	ret := _m.Called(artifactId)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(artifactId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
