// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	domain "github.com/startup-of-zero-reais/COD-courses-api/domain"
	mock "github.com/stretchr/testify/mock"
)

// ModuleService is an autogenerated mock type for the ModuleService type
type ModuleService struct {
	mock.Mock
}

// Add provides a mock function with given fields: module
func (_m *ModuleService) Add(module domain.Module) (*domain.Module, error) {
	ret := _m.Called(module)

	var r0 *domain.Module
	if rf, ok := ret.Get(0).(func(domain.Module) *domain.Module); ok {
		r0 = rf(module)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Module)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.Module) error); ok {
		r1 = rf(module)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: moduleID
func (_m *ModuleService) Delete(moduleID string) error {
	ret := _m.Called(moduleID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(moduleID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: moduleID
func (_m *ModuleService) Get(moduleID string) (*domain.Module, error) {
	ret := _m.Called(moduleID)

	var r0 *domain.Module
	if rf, ok := ret.Get(0).(func(string) *domain.Module); ok {
		r0 = rf(moduleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Module)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(moduleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByCourses provides a mock function with given fields: courseID, pagination
func (_m *ModuleService) ListByCourses(courseID string, pagination map[string]string) ([]domain.Module, error) {
	ret := _m.Called(courseID, pagination)

	var r0 []domain.Module
	if rf, ok := ret.Get(0).(func(string, map[string]string) []domain.Module); ok {
		r0 = rf(courseID, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Module)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, map[string]string) error); ok {
		r1 = rf(courseID, pagination)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: module
func (_m *ModuleService) Save(module domain.Module) (*domain.Module, error) {
	ret := _m.Called(module)

	var r0 *domain.Module
	if rf, ok := ret.Get(0).(func(domain.Module) *domain.Module); ok {
		r0 = rf(module)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Module)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.Module) error); ok {
		r1 = rf(module)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
