// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	domain "github.com/startup-of-zero-reais/COD-courses-api/domain"
	mock "github.com/stretchr/testify/mock"
)

// SectionRepository is an autogenerated mock type for the SectionRepository type
type SectionRepository struct {
	mock.Mock
}

// Count provides a mock function with given fields:
func (_m *SectionRepository) Count() uint {
	ret := _m.Called()

	var r0 uint
	if rf, ok := ret.Get(0).(func() uint); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint)
	}

	return r0
}

// Create provides a mock function with given fields: section
func (_m *SectionRepository) Create(section domain.Section) (*domain.Section, error) {
	ret := _m.Called(section)

	var r0 *domain.Section
	if rf, ok := ret.Get(0).(func(domain.Section) *domain.Section); ok {
		r0 = rf(section)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Section)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.Section) error); ok {
		r1 = rf(section)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: sectionID
func (_m *SectionRepository) Delete(sectionID string) error {
	ret := _m.Called(sectionID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(sectionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: search, pagination
func (_m *SectionRepository) Get(search map[string]string, pagination map[string]string) ([]domain.Section, error) {
	ret := _m.Called(search, pagination)

	var r0 []domain.Section
	if rf, ok := ret.Get(0).(func(map[string]string, map[string]string) []domain.Section); ok {
		r0 = rf(search, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Section)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(map[string]string, map[string]string) error); ok {
		r1 = rf(search, pagination)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: section
func (_m *SectionRepository) Save(section domain.Section) (*domain.Section, error) {
	ret := _m.Called(section)

	var r0 *domain.Section
	if rf, ok := ret.Get(0).(func(domain.Section) *domain.Section); ok {
		r0 = rf(section)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Section)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.Section) error); ok {
		r1 = rf(section)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
